config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#index"
  post "ajax_call", to: "home#ajax_call"
  devise_for :users
  namespace :api do
    get 'private_api', to: 'test#private_api'
    get 'public_api', to: 'test#public_api'
    post 'authenticate', to: 'base#authenticate'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  enum role: {seller: 0, buyer: 1, admin: 2}
end

app/controllers/api/base_controller.rb
class Api::BaseController < ApplicationController
  def authenticate
    result = AuthenticateUser.new(params[:email], params[:password]).call
    if result[:success]
      render json: { auth_token: result[:token] }
    else
      render json: { error: result[:error] }, status: :unauthorized
    end
  end

  def authenticate_request
    @current_user = AuthorizeApiRequest.new(request.headers).call
    render json: { error: 'Not Authorized' }, status: 401 unless @current_user
  end
end

app/controllers/api/test_controller.rb
class Api::TestController < Api::BaseController
  before_action :authenticate_request, only: :private_api
  def private_api
    render json: {status: :success}
  end

  def public_api
    render json: {status: :success}
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?
  skip_before_action :verify_authenticity_token

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:role, :email, :password)}

    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:role, :email, :password, :current_password)}
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	end

	def ajax_call
	  user_id = User.find_by_email(params[:email]).id
	  render json: {user_id: user_id}
	end
end

app/helpers/api/base_helper.rb
module Api::BaseHelper
end

app/helpers/api/test_helper.rb
module Api::TestHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/ajax_call.html.erb
<p><%= @user_id %></p>

app/views/home/index.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Email</th>
      <th scope="col">Role</th>
      <th scope="col">Trigger</th>
      <th scope="col">Response</th>
    </tr>
  </thead>
  <tbody>
    <% User.all.each do |user|%>
      <tr>
        <td ><%= user.email %></td>
        <td><%= user.role %></td>
        <td><button onclick='submitAjaxcall("<%= user.email %>");' >Click to trigger</button></td>
        <td id="aja_response_<%= user.id%>">ajax response</td>
      </tr>
    <% end %>
  </tbody>
</table>
<script>
    // Rails.ajax has to url encode post params
    toURLEncoded = function(element) {
      var key, list;
      list = [];
      if ('object' === typeof element) {
        for (key in element) {
          key = key;
          if (element.hasOwnProperty(key)) {
            list.push(key + '=' + encodeURIComponent(element[key]));
          }
        }
      }
      return list.join('&');
    };

    function submitAjaxcall(email){
      var email = email
      const person = {firstName:"John", lastName:"Doe", age:50, eyeColor:"blue"};
      Rails.ajax({
        type: "POST", 
        url: "<%= ajax_call_path %>",
        data: toURLEncoded({email: email}),
        success: function (response) {
          var id = "aja_response_" + response.user_id
          document.getElementById(id).innerHTML = response.user_id;}
      })
    }
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ecommerce</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
     <p class="notice"><%= notice %></p>
     <p class="alert"><%= alert %></p>
      <p class="navbar-text float-right">
      <% if user_signed_in? %>
        Logged in as <strong><%= current_user.email %></strong>.
        <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
        <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
      <% else %>
        <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
        <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
      <% end %>
      </p>
    <%= yield %>
  </body>
</html>